apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: opencasts.opencast.example.com
spec:
  group: opencast.example.com
  names:
    kind: Opencast
    listKind: OpencastList
    plural: opencasts
    singular: opencast
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
