apiVersion: opencast.example.com/v1alpha1
kind: Opencast
metadata:
  name: example-opencast
spec:
  # Add fields here
  # Storage settings
  createpv: yes
  pvsize: 20Gi
  # General opencast configuration settings
  opencast:
    database:
      url: jdbc:mysql://localhost/opencast
      user: opencast
      pass: opencast
    digest:
      pass: CHANGE_ME
    activemq:
      url: failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      username: opencast
      pass: opencast
    server:
      url: https://example.opencast.org
    lti:
      highly_trusted_consumer_key: opencast
    oauth:
      consumer:
        name: opencast
        key: opencast
        secret: opencast
    admin:
      pass: opencast
      ui:
        url: https://example.opencast.org
    engage:
      ui:
        url: https://example.opencast.org
    #LDAP userdirectory
    userdirectory:
      ldap:
        id: example
        url: ldaps://example.opencast.org:636
        searchbase: dc=opencast,dc=org
        searchfilter: (uid={0})
        roleattributes: objectClass
        userdn: cn=opencast,ou=applications,dc=opencast,dc=org
        password: example
    # CAS login filter
    cas_filter:
      login_url:
      service:
      ticket_validator:
      logout_url:
      logout_filter_url:
  # Type of deploy, options are allinone, admin, presentation, worker, ingest.
  opencast-allinone:
  # Resource constraints for allinone installation
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 1Gi
        cpu: 1
  # opencast-admin:
    # resources:
      # requests:
      #   memory: 1Gi
      #   cpu: 1
      # limits:
      #   memory: 1Gi
      #   cpu: 1
  # opencast-presentation:
    # resources:
      # requests:
      #   memory: 1Gi
      #   cpu: 1
      # limits:
      #   memory: 1Gi
      #   cpu: 1
  # opencast-worker:
    # replicas: 1
    # resources:
      # requests:
      #   memory: 1Gi
      #   cpu: 1
      # limits:
      #   memory: 1Gi
      #   cpu: 1
  # opencast-ingest:
    # replicas: 1
    # resources:
      # requests:
      #   memory: 1Gi
      #   cpu: 1
      # limits:
      #   memory: 1Gi
      #   cpu: 1

