apiVersion: opencast.example.com/v1alpha1
kind: Opencast
metadata:
  name: example-opencast
spec:
  # Add fields here
  # Storage settings
  # Either have the operator create a pv or provide the pvc name via the claimName setting
  createpv: yes
  pvsize: 20Gi
  # claimname: opencast
  # General opencast configuration settings
  opencast:
    database:
      url: jdbc:mysql://localhost/opencast
      user: opencast
      pass: opencast
    digest:
      pass: CHANGE_ME
    activemq:
      url: failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      username: opencast
      pass: opencast
    # lti:
    #   highly_trusted_consumer_key: opencast
    # oauth:
    #   consumer:
    #     name: opencast
    #     key: opencast
    #     secret: opencast
    admin:
      pass: opencast
      ui:
        url: https://example.opencast.org
    engage:
      ui:
        url: https://example.opencast.org

    #LDAP userdirectory
    # userdirectory:
    #   ldap:
    #     id: example
    #     url: ldaps://example.opencast.org:636
    #     searchbase: dc=opencast,dc=org
    #     searchfilter: (uid={0})
    #     roleattributes: objectClass
    #     userdn: cn=opencast,ou=applications,dc=opencast,dc=org
    #     password: example
    # Matomo tracking
    # matomo:
    #   server:
    #   site_id:
  # Type of deploy, options are allinone, admin, presentation, worker, ingest.
  opencast_allinone:
    # deploy specific variables
    server:
      url: https://example.opencast.org
    # CAS login filter
    # cas_filter:
    #   login_url:
    #   service:
    #   ticket_validator:
    #   logout_url:
    #   logout_filter_url:
  # Resource constraints for allinone installation
    java:
      min_mem: 512M
      max_mem: 2G
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 1Gi
        cpu: 1
  # opencast-admin:
    # server:
    #   url: https://example.opencast.org
    # java:
    #   min_mem: 512M
    #   max_mem: 2G
    # resources:
      # requests:
      #   memory: 1Gi
      #   cpu: 1
      # limits:
      #   memory: 1Gi
      #   cpu: 1
  # opencast-presentation:
    # server:
    #   url: https://example.opencast.org
    # java:
    #   min_mem: 512M
    #   max_mem: 2G
    # resources:
      # requests:
      #   memory: 1Gi
      #   cpu: 1
      # limits:
      #   memory: 1Gi
      #   cpu: 1
  # opencast-worker:
    # replicas: 1
    # java:
    #   min_mem: 512M
    #   max_mem: 2G
    # resources:
      # requests:
      #   memory: 1Gi
      #   cpu: 1
      # limits:
      #   memory: 1Gi
      #   cpu: 1
  # opencast-ingest:
    # replicas: 1
    # java:
    #   min_mem: 512M
    #   max_mem: 2G
    # resources:
      # requests:
      #   memory: 1Gi
      #   cpu: 1
      # limits:
      #   memory: 1Gi
      #   cpu: 1

