---
apiVersion: v1
kind: Deployment
metadata:
  name: activemq
  namespace: '{{ meta.namespace }}'
  labels:
    name: activemq
    app: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      restartPolicy: Always
      containers:
        - name: activemq
          image: quay.io/mm-dict/activemq-opencast:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 61616
              protocol: TCP
          env:
            - name: ACTIVEMQ_MIN_MEMORY
              value: "128"
            - name: ACTIVEMQ_MAX_MEMORY
              value: "1024"
            - name: ACTIVEMQ_ENABLED_SCHEDULER
              value: "true"
            - name: ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT
              value: "true"
            - name: ACTIVEMQ_OWNER_LOGIN
              value: "opencast"
            - name: ACTIVEMQ_OWNER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-activemq'
                  key: activemq-password
          volumeMounts:
            - name: activemq-persistent-storage
              mountPath: /opt/activemq/data
            - name: activemq-config
              mountPath: /opt/activemq/conf/activemq.xml
              subPath: activemq.xml
          resources:
            requests:
              memory: 1Gi
              cpu: 800m
            limits:
              memory: 2Gi
              cpu: 2
      volumes:
        - name: activemq-config
          configMap:
            name: activemq-config
        - name: activemq-persistent-storage
          persistentVolumeClaim:
            claimName: activemq
