---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ meta.name }}-opencast-allinone'
  namespace: '{{ meta.namespace }}'
  labels:
    app: opencast
    type: allinone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencast
  template:
    metadata:
      labels:
        app: opencast
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: opencast
      containers:
        - name: opencast-allinone
          image: '{{ opencast-allinone.image }}'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ORG_OPENCASTPROJECT_DB_VENDOR
              value: "MySQL"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_URL
              value: "{{ opencast.database.url }}"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_USER
              value: "{{ opencast.database.user }}"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_DRIVER
              value: "com.mysql.cj.jdbc.Driver"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-database'
                  key: database-password
            - name: JAVA_MIN_MEM
              value: "512M"
            - name: JAVA_MAX_MEM
              value: "5G"
            - name: ORG_OPENCASTPROJECT_SERVER_URL
              value: "{{ opencast.server.url }}"
            - name: ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER
              value: "admin"
            - name: ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast'
                  key: admin-pass
            - name: ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER
              value: "opencast_system_account"
            - name: ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast'
                  key: digest-pass
            - name: ACTIVEMQ_BROKER_URL
              value: "{{ opencast.activemq.url }}"
            - name: ACTIVEMQ_BROKER_USERNAME
              value: "{{ opencast.activemq.username }}"
            - name: ACTIVEMQ_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-activemq'
                  key: activemq-password
            - name: KARAF_ETC
              value: "/opencast/etc"
            - name: LOG_LEVEL
              value: "INFO"
            - name: PROP_ORG_OPENCASTPROJECT_PLAYER
              value: "/paella/ui/watch.html?id=#{id}"
            - name: ORG_OPENCASTPROJECT_STREAMING_URL
              value: {{ opencast.streaming.url }}
            - name: ORG_OPENCASTPROJECT_ADAPTIVE_STREAMING_URL
              value: {{ opencast.adaptive_streaming.url }}
          volumeMounts:
            - name: opencast-persistent-storage
              mountPath: /data
              {% if storage.subpath is defined %}
              subPath: {{ storage.subpath }}
              {% endif %}
          resources:
            requests:
              memory: "{{ opencast-allinone.resources.requests.memory }}"
              cpu: "{{ opencast-allinone.resources.requests.cpu }}"
            limits:
              memory: "{{ opencast-allinone.resources.limits.memory }}"
              cpu: "{{ opencast-allinone.resources.limits.cpu }}"
      volumes:
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: opencast-data
