#jinja2: lstrip_blocks: "True", trim_blocks: "True"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: '{{ meta.name }}-opencast-ingest'
  namespace: '{{ meta.namespace }}'
  labels:
    app: opencast
    type: ingest
spec:
  replicas: {{ opencast_ingest.replicas | default(1) }}
  serviceName: '{{ meta.name }}-opencast-ingest'
  selector:
    matchLabels:
      app: opencast
      type: ingest
  minReadySeconds: 60
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: opencast
        type: ingest
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: opencast
      containers:
        - name: opencast-ingest
          image: '{{ opencast_ingest.image }}'
          imagePullPolicy: Always
          {% if runasuser is defined %}
          securityContext:
            runAsUser: {{ runasuser }}
          {% endif %}
          ports:
            - containerPort: 8080
          env:
            - name: ORG_OPENCASTPROJECT_SERVER_URL
              value: "{{ opencast_ingest.server.url }}"
            - name: ORG_OPENCASTPROJECT_DB_VENDOR
              value: "MariaDB"
            - name: JAVA_MIN_MEM
              value: "{{ opencast_ingest.java.min_mem }}"
            - name: JAVA_MAX_MEM
              value: "{{ opencast_ingest.java.max_mem }}"
            - name: ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER
              value: "admin"
            - name: ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast'
                  key: admin-pass
            - name: ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER
              value: "opencast_system_account"
            - name: ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast'
                  key: digest-pass
            - name: ORG_OPENCASTPROJECT_DB_JDBC_URL
              value: "{{ opencast.database.url }}"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_USER
              value: "{{ opencast.database.user }}"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_DRIVER
              value: "org.mariadb.jdbc.Driver"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-database'
                  key: database-password
            - name: ORG_OPENCASTPROJECT_STREAMING_URL
              value: {{ opencast.streaming.url }}
            - name: ORG_OPENCASTPROJECT_ADAPTIVE_STREAMING_URL
              value: {{ opencast.adaptive_streaming.url }}
            - name: ACTIVEMQ_BROKER_URL
              value: "{{ opencast.activemq.url }}"
            - name: ACTIVEMQ_BROKER_USERNAME
              value: "{{ opencast.activemq.user}}"
            - name: ACTIVEMQ_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-activemq'
                  key: activemq-password
            - name: PROP_ORG_OPENCASTPROJECT_PLAYER
              value: "{{ opencast.player | default('/paella/ui/watch.html?id=#{id}') }}"
            - name: PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL
              value: "{{ opencast.admin.ui.url }}"
            - name: PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL
              value: "{{ opencast.engage.ui.url }}"
            - name: ELASTICSEARCH_SERVER_ADDRESS
              value: "{{ opencast.elasticsearch.address }}"
            - name: ELASTICSEARCH_SERVER_PORT
              value: "9200"
          volumeMounts:
            - name: opencast-persistent-storage
              mountPath: /data/opencast
              {% if storage.subpath is defined %}
              subPath: {{ storage.subpath }}
              {% endif %}
            - name: opencast-config
              mountPath: /opencast-custom
              subPath: generic
          resources:
            {% if opencast_ingest.resources.requests is defined %}
            requests:
              memory: "{{ opencast_ingest.resources.requests.memory }}"
              cpu: "{{ opencast_ingest.resources.requests.cpu }}"
            {% endif %}
            {% if opencast_ingest.resources.limits is defined %}
            limits:
              memory: "{{ opencast_ingest.resources.limits.memory }}"
              cpu: "{{ opencast_ingest.resources.limits.cpu }}"
            {% endif %}
      volumes:
        {% if createpv is defined %}
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: opencast-data
        {% else %}
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: {{ storage.claimname }}
        {% endif %}
        - name: opencast-config
          persistentVolumeClaim:
            claimName: {{ meta.name }}-opencast-config
