---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: '{{ meta.name }}-opencast-worker'
  namespace: '{{ meta.namespace }}'
  labels:
    app: opencast
    type: worker
spec:
  replicas: {{ opencast-worker.replicas }}
  serviceName: opencast-worker
  selector:
    matchLabels:
      app: opencast
      type: worker
  template:
    metadata:
      labels:
        app: opencast
        type: worker
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      containers:
        - name: opencast-worker
          image: '{{ opencast-worker.image }}'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: ORG_OPENCASTPROJECT_DB_VENDOR
              value: "MySQL"
            - name: JAVA_MIN_MEM
              value: "512M"
            - name: JAVA_MAX_MEM
              value: "4G"
            - name: ORG_OPENCASTPROJECT_SERVER_URL
              value: "{{ opencast.server.url }}"
            - name: ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER
              value: "admin"
            - name: ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast'
                  key: admin-pass
            - name: ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER
              value: "opencast_system_account"
            - name: ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast'
                  key: digest-pass
            - name: ORG_OPENCASTPROJECT_DB_JDBC_URL
              value: "{{ opencast.database.url }}"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_USER
              value: "{{ opencast.database.user }}"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_DRIVER
              value: "com.mysql.cj.jdbc.Driver"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-allinone-database'
                  key: database-password
            - name: ORG_OPENCASTPROJECT_STREAMING_URL
              value: {{ opencast.streaming.url }}
            - name: ORG_OPENCASTPROJECT_ADAPTIVE_STREAMING_URL
              value: {{ opencast.adaptive_streaming.url }}
            - name: ACTIVEMQ_BROKER_URL
              value: "{{ opencast.activemq.url }}"
            - name: ACTIVEMQ_BROKER_USERNAME
              value: "{{ opencast.activemq.user}}"
            - name: ACTIVEMQ_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-activemq'
                  key: opencast-password
            - name: PROP_ORG_OPENCASTPROJECT_PLAYER
              value: "/paella/ui/watch.html?id=#{id}"
          volumeMounts:
            - name: opencast-persistent-storage
              mountPath: /data
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.kernel.security.LtiLaunchAuthenticationHandler.cfg
              subPath: org.opencastproject.kernel.security.LtiLaunchAuthenticationHandler.cfg
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.kernel.security.OAuthConsumerDetailsService.cfg
              subPath: org.opencastproject.kernel.security.OAuthConsumerDetailsService.cfg
            - name: opencast-config
              mountPath: /opencast/etc/paella/config/config.json
              subPath: paella-config.json
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.organization-mh_default_org.cfg
              subPath: org.opencastproject.organization-mh_default_org.cfg
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.userdirectory.brightspace-default.cfg
              subPath: org.opencastproject.userdirectory.brightspace-default.cfg
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.distribution.streaming.wowza.WowzaAdaptiveStreamingDistributionService.cfg
              subPath: org.opencastproject.distribution.streaming.wowza.WowzaAdaptiveStreamingDistributionService.cfg
          resources:
            requests:
              memory: "{{ opencast-worker.resources.requests.memory }}"
              cpu: "{{ opencast-worker.resources.requests.cpu }}"
            limits:
              memory: "{{ opencast-worker.resources.limits.memory }}"
              cpu: "{{ opencast-worker.resources.limits.cpu }}"
      volumes:
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: opencast-data
        - name: opencast-config
          configMap:
            name: opencast-config
