#jinja2: lstrip_blocks: "True", trim_blocks: "True"
---
apiVersion: v1
kind: Deployment
metadata:
  name: '{{ meta.name }}-opencast-admin'
  namespace: '{{ meta.namespace }}'
  labels:
    app: opencast
    type: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      type: admin
      app: opencast
  template:
    metadata:
      labels:
        app: opencast
        type: admin
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: opencast
      containers:
        - name: opencast-admin
          image: '{{ opencast_admin.image }}'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_MIN_MEM
              value: "{{ opencast_admin.java.min_mem}}"
            - name: JAVA_MAX_MEM
              value: "{{ opencast_admin.java.max_mem}}"
            - name: OPENCAST_DISABLE_CONFIG
              value: "true"
          volumeMounts:
            - name: opencast-persistent-storage
              mountPath: /data
              {% if storage.subpath is defined %}
              subPath: {{ storage.subpath }}
              {% endif %}
            - name: opencast-admin-config
              mountPath: /opencast/etc/custom.properties
              subPath: custom.properties
            - name: opencast-config
              mountPath: /opencast/etc/paella/config/config.json
              subPath: paella-config.json
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.organization-mh_default_org.cfg
              subPath: org.opencastproject.organization-mh_default_org.cfg
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.distribution.streaming.wowza.WowzaAdaptiveStreamingDistributionService.cfg
              subPath: org.opencastproject.distribution.streaming.wowza.WowzaAdaptiveStreamingDistributionService.cfg
            - name: opencast-config
              mountPath: /opencast/etc/workflows/ugent-schedule-and-upload.xml
              subPath: ugent-schedule-and-upload.xml
            - name: opencast-config
              mountPath: /opencast/etc/workflows/ugent-partial-publish.xml
              subPath: ugent-partial-publish.xml
            - name: opencast-admin-data
              mountPath: /opencast/data
            {% if opencast.lti is defined %}
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg
              subPath: org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.kernel.security.OAuthConsumerDetailsService.cfg
              subPath: org.opencastproject.kernel.security.OAuthConsumerDetailsService.cfg
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.lti.endpoint.EventsEndpoint.cfg
              subPath: org.opencastproject.lti.endpoint.EventsEndpoint.cfg
            {% endif %}
            {% if opencast_admin.cas_filter is defined %}
            - name: opencast-admin-config
              mountPath: /opencast/etc/security/mh_default_org.xml
              subPath: mh_default_org.xml
            - name: opencast-admin-config
              mountPath: /opencast/etc/org.apache.karaf.features.cfg
              subPath: org.apache.karaf.features.cfg
            {% endif %}
            {% if opencast.userdirectory.ldap is defined %}
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.userdirectory.ldap-{{ opencast.userdirectory.ldap.id }}.cfg
              subPath: org.opencastproject.userdirectory.ldap-{{ opencast.userdirectory.ldap.id }}.cfg
            {% endif %}
            {% if extra_ldap is defined %}
            - name: {{ extra_ldap.name }}
              mountPath: {{ extra_ldap.configmap.mountpath }}
              subPath: {{ extra_ldap.configmap.subpath }}
            {% endif %}
          resources:
            requests:
              memory: "{{ opencast_admin.resources.requests.memory }}"
              cpu: "{{ opencast_admin.resources.requests.cpu }}"
            limits:
              memory: "{{ opencast_admin.resources.limits.memory }}"
              cpu: "{{ opencast_admin.resources.limits.cpu }}"
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            httpGet:
              path: /info/me.json
              port: 8080
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: localhost
      volumes:
        - name: opencast-config
          configMap:
            name: {{ meta.name }}-opencast-config
        - name: opencast-admin-config
          configMap:
            name: {{ meta.name }}-opencast-admin-config
        {% if createpv is defined %}
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: opencast-data
        {% else %}
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: {{ storage.claimname }}
        {% endif %}
        {% if extra_ldap is defined %}
        - name: {{ extra_ldap.name }}
          configMap:
            name: {{ extra_ldap.configmap.name }}
        {% endif %}
        - name: opencast-admin-data
          emptyDir: {}
