#jinja2: lstrip_blocks: "True", trim_blocks: "True"
---
apiVersion: v1
kind: Deployment
metadata:
  name: '{{ meta.name }}-opencast-presentation'
  namespace: '{{ meta.namespace }}'
  labels:
    app: opencast
    type: presentation
spec:
  replicas: 1
  selector:
    matchLabels:
      type: presentation
      app: opencast
  template:
    metadata:
      labels:
        app: opencast
        type: presentation
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: opencast
      containers:
        - name: opencast-presentation
          image: '{{ opencast_presentation.image }}'
          imagePullPolicy: Always
          {% if runasuser is defined %}
          securityContext:
            runAsUser: {{ runasuser }}
          {% endif %}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_MIN_MEM
              value: "{{ opencast_presentation.java.min_mem}}"
            - name: JAVA_MAX_MEM
              value: "{{ opencast_presentation.java.max_mem}}"
            - name: OPENCAST_DISABLE_CONFIG
              value: "true"
          volumeMounts:
            - name: opencast-persistent-storage
              mountPath: /data/opencast
            - name: opencast-config
              mountPath: /opencast/etc/paella/config/config.json
              subPath: paella-config.json
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.organization-mh_default_org.cfg
              subPath: org.opencastproject.organization-mh_default_org.cfg
            - name: opencast-presentation-config
              mountPath: /opencast/etc/custom.properties
              subPath: custom.properties
            - name: opencast-presentation-config
              mountPath: /opencast/bin/setenv
              subPath: setenv
            - name: opencast-presentation-data
              mountPath: /opencast/data
            - name: opencast-config
              mountPath: /opencast/etc/workflows/ugent-schedule-and-upload.xml
              subPath: ugent-schedule-and-upload.xml
            - name: opencast-config
              mountPath: /opencast/etc/workflows/ugent-partial-publish.xml
              subPath: ugent-partial-publish.xml
            {% if opencast.lti is defined %}
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg
              subPath: org.opencastproject.security.lti.LtiLaunchAuthenticationHandler.cfg
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.kernel.security.OAuthConsumerDetailsService.cfg
              subPath: org.opencastproject.kernel.security.OAuthConsumerDetailsService.cfg
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.lti.service.impl.LtiServiceImpl.cfg
              subPath: org.opencastproject.lti.service.impl.LtiServiceImpl.cfg
            {% endif %}
            {% if opencast_presentation.cas_filter is defined %}
            - name: opencast-presentation-config
              mountPath: /opencast/etc/security/mh_default_org.xml
              subPath: mh_default_org.xml
            - name: opencast-presentation-config
              mountPath: /opencast/etc/org.apache.karaf.features.cfg
              subPath: org.apache.karaf.features.cfg
            {% endif %}
            {% if opencast.userdirectory.ldap is defined %}
            - name: opencast-config
              mountPath: /opencast/etc/org.opencastproject.userdirectory.ldap-{{ opencast.userdirectory.ldap.id }}.cfg
              subPath: org.opencastproject.userdirectory.ldap-{{ opencast.userdirectory.ldap.id }}.cfg
            {% endif %}
            {% if extra_ldap is defined %}
            - name: {{ extra_ldap.name }}
              mountPath: {{ extra_ldap.configmap.mountpath }}
              subPath: {{ extra_ldap.configmap.subpath }}
            {% endif %}
          resources:
            {% if opencast_presentation.resources.requests is defined %}
            requests:
              memory: "{{ opencast_presentation.resources.requests.memory }}"
              cpu: "{{ opencast_presentation.resources.requests.cpu }}"
            {% endif %}
            {% if opencast_presentation.resources.limits is defined %}
            limits:
              memory: "{{ opencast_presentation.resources.limits.memory }}"
              cpu: "{{ opencast_presentation.resources.limits.cpu }}"
            {% endif %}
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 120
            httpGet:
              path: /info/me.json
              port: 8080
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: localhost
          livenessProbe:
            initialDelaySeconds: 240
            periodSeconds: 60
            httpGet:
              path: /info/me.json
              port: 8080
              scheme: HTTP
              httpHeaders:
              - name: Host
                value: localhost
      volumes:
        - name: opencast-presentation-config
          configMap:
            name: {{ meta.name }}-opencast-presentation-config
        {% if createpv is defined %}
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: opencast-data
        {% else %}
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: {{ storage.claimname }}
        {% endif %}
        - name: opencast-config
          configMap:
            name: {{ meta.name }}-opencast-config
        - name: opencast-presentation-data
          emptyDir: {}
        {% if extra_ldap is defined %}
        - name: {{ extra_ldap.name }}
          configMap:
            name: {{ extra_ldap.name }}
        {% endif %}
