#jinja2: lstrip_blocks: "True", trim_blocks: "True"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: '{{ meta.name }}-opencast-worker'
  namespace: '{{ meta.namespace }}'
  labels:
    app: opencast
    type: worker
spec:
  replicas: {{ opencast_worker.replicas }}
  serviceName: '{{ meta.name }}-opencast-worker'
  selector:
    matchLabels:
      app: opencast
      type: worker
  template:
    metadata:
      labels:
        app: opencast
        type: worker
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      serviceAccountName: opencast
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "opencast-worker"
          effect: "NoSchedule"
      containers:
        - name: opencast-worker
          image: '{{ opencast_worker.image }}'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
          env:
            - name: ORG_OPENCASTPROJECT_DB_VENDOR
              value: "MySQL"
            - name: JAVA_MIN_MEM
              value: "{{ opencast_worker.java.min_mem}}"
            - name: JAVA_MAX_MEM
              value: "{{ opencast_worker.java.max_mem}}"
            - name: ORG_OPENCASTPROJECT_SERVER_URL
              value: ""
            - name: ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER
              value: "admin"
            - name: ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast'
                  key: admin-pass
            - name: ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER
              value: "opencast_system_account"
            - name: ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast'
                  key: digest-pass
            - name: ORG_OPENCASTPROJECT_DB_JDBC_URL
              value: "{{ opencast.database.url }}"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_USER
              value: "{{ opencast.database.user }}"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_DRIVER
              value: "com.mysql.cj.jdbc.Driver"
            - name: ORG_OPENCASTPROJECT_DB_JDBC_PASS
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-database'
                  key: database-password
            - name: ORG_OPENCASTPROJECT_STREAMING_URL
              value: {{ opencast.streaming.url }}
            - name: ORG_OPENCASTPROJECT_ADAPTIVE_STREAMING_URL
              value: {{ opencast.adaptive_streaming.url }}
            - name: ACTIVEMQ_BROKER_URL
              value: "{{ opencast.activemq.url }}"
            - name: ACTIVEMQ_BROKER_USERNAME
              value: "{{ opencast.activemq.user}}"
            - name: ACTIVEMQ_BROKER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ meta.name }}-opencast-activemq'
                  key: activemq-password
            - name: PROP_ORG_OPENCASTPROJECT_PLAYER
              value: "/paella/ui/watch.html?id=#{id}"
            - name: PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL
              value: "{{ opencast.admin.ui.url }}"
            - name: PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL
              value: "{{ opencast.engage.ui.url }}"
            - name: SOLR_SEARCH_URL
              value: "{{ opencast.solr_search.url }}"
            - name: SOLR_SERIES_URL
              value: "{{ opencast.solr_series.url }}"
            - name: SOLR_WORKFLOW_URL
              value: "{{ opencast.solr_workflow.url }}"
            - name: ELASTIC_SERVER_ADDRESS
              value: "{{ opencast.elasticsearch.address }}"
            - name: ELASTIC_SERVER_PORT
              value: "9200"
          volumeMounts:
            - name: opencast-persistent-storage
              mountPath: /data
              {% if storage.subpath is defined %}
              subPath: {{ storage.subpath }}
              {% endif %}
            - name: opencast-worker-data
              mountPath: /opencast/data
            - name: opencast-config
              mountPath: /opencast/etc/workflows/ugent-schedule-and-upload.xml
              subPath: ugent-schedule-and-upload.xml
            - name: opencast-config
              mountPath: /opencast/etc/workflows/ugent-partial-publish.xml
              subPath: ugent-partial-publish.xml
            {% for volume in custom_volumes %}
            - name: {{ volume.name }}
              mountPath: {{ volume.configmap.mountpath }}
              subPath: {{ volume.configmap.subpath }}
            {% endfor %}
          resources:
            requests:
              memory: "{{ opencast_worker.resources.requests.memory }}"
              cpu: "{{ opencast_worker.resources.requests.cpu }}"
      volumes:
        {% if createpv is defined %}
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: opencast-data
        {% else %}
        - name: opencast-persistent-storage
          persistentVolumeClaim:
            claimName: {{ claimname }}
        {% endif %}
        - name: opencast-worker-data
          emptyDir: {}
        - name: opencast-config
          configMap:
            name: {{ meta.name }}-opencast-config
        {% for volume in custom_volumes %}
        - name: {{ volume.name }}
          configMap:
            name: {{ volume.configmap.name }}
        {% endfor %}