---
- name: Create the activemq service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: '{{ meta.name }}-activemq'
        namespace: '{{ meta.namespace }}'
        labels:
          app: activemq
      spec:
        selector:
          app: activemq
        ports:
          - port: 61616
        clusterIP: None

- name: Create the configmap for activemq
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/activemq-configmap.yml') }}"

- name: Create the deployment for activemq
  k8s:
    state: present
    definition: "{{ lookup('template', 'templates/activemq-statefulset.yml') }}"