---
- name: Create the serviceaccount
  k8s:
    state: present
    api_version: v1
    kind: ServiceAccount
    name: opencast
    namespace: '{{ meta.namespace }}'

- name: Create the secret for opencast login
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: '{{ meta.namespace }}'
        name: '{{ meta.name }}-opencast'
      data:
        admin-pass: '{{ opencast.admin.pass | string | b64encode  }}'
        digest-pass: '{{ opencast.digest.pass | string | b64encode  }}'

- name: Create the secret for the database login
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: '{{ meta.namespace }}'
        name: '{{ meta.name }}-opencast-database'
      data:
        database-password: '{{ opencast.database.pass | string | b64encode  }}'

- name: Create the secret for activemq login
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        namespace: '{{ meta.namespace }}'
        name: '{{ meta.name }}-opencast-activemq'
      data:
        activemq-password: '{{ opencast.activemq.pass | string | b64encode  }}'

- name: Create the PV when defined in the spec
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: '{{ meta.namespace }}'
        name: opencast-data
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: '{{ pvsize }}'
  when: createpv is defined

- name: Create the general opencast configmap
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'templates/opencast-configmap.yml') }}"

- name: Include the activemq tasks
  include: activemq.yml

- name: Include the solr-series tasks
  include: solr-series.yml
  when: opencast.solr_series is defined

- name: Include the solr-search tasks
  include: solr-search.yml
  when: opencast.solr_search is defined

- name: Include the solr-workflow tasks
  include: solr-workflow.yml
  when: opencast.solr_workflow is defined

- name: Include the elastic tasks
  include: elastic.yml
  when: opencast.elasticsearch is defined

- name: Include the opencast allinone tasks
  include: opencastallinone.yml
  when: opencast_allinone is defined

- name: Include the opencast admin tasks
  include: opencastadmin.yml
  when: opencast_admin is defined

- name: Include the opencast presentation tasks
  include: opencastpresentation.yml
  when: opencast_presentation is defined

- name: Include the opencast worker tasks
  include: opencastworker.yml
  when: opencast_worker is defined

- name: Include the opencast ingest tasks
  include: opencastingest.yml
  when: opencast_ingest is defined