---
- name: Create the solr-series PV
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        namespace: '{{ meta.namespace }}'
        name: solr-series
      spec:
        accessModes:
          - ReadWriteMany
        resources:
          requests:
            storage: '{{ opencast.solr_series.pvsize | default("100Mi") }}'

- name: Create the solr-series service
  k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: solr-series
        namespace: '{{ meta.namespace }}'
        labels:
          app: solr-series
      spec:
        selector:
          app: solr-series
        ports:
          - port: 8080

- name: set the solr type as a fact
  set_fact:
    type: series

- name: Create the deployment for solr-series
  k8s:
    state: present
    apply: yes
    definition: "{{ lookup('template', 'templates/solr-deployment.yml') }}"